export const ticketsData = [
    {
        "id": 1,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "16:20",
        "arrival_date": "12.05.18",
        "arrival_time": "22:10",
        "carrier": "TK",
        "stops": 3,
        "prices": {
            "price_rub": 12400,
            "price_usd": 189.2,
            "price_eur": 166.63
        }
    }, {
        "id": 2,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "17:20",
        "arrival_date": "12.05.18",
        "arrival_time": "23:50",
        "carrier": "S7",
        "stops": 1,
        "prices": {
            "price_rub": 13100,
            "price_usd": 199.88,
            "price_eur": 176.04
        }
    }, {
        "id": 3,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "12:10",
        "arrival_date": "12.05.18",
        "arrival_time": "18:10",
        "carrier": "SU",
        "stops": 0,
        "prices": {
            "price_rub": 15300,
            "price_usd": 233.44,
            "price_eur": 205.6
        }
    }, {
        "id": 4,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "17:00",
        "arrival_date": "12.05.18",
        "arrival_time": "23:30",
        "carrier": "TK",
        "stops": 2,
        "prices":{
            "price_rub": 11000,
            "price_usd": 167.84,
            "price_eur": 147.82
        }
    }, {
        "id": 5,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "12:10",
        "arrival_date": "12.05.18",
        "arrival_time": "20:15",
        "carrier": "BA",
        "stops": 3,
        "prices": {
            "price_rub": 13400,
            "price_usd": 204.45,
            "price_eur": 180.07
        }
    }, {
        "id": 6,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "9:40",
        "arrival_date": "12.05.18",
        "arrival_time": "19:25",
        "carrier": "SU",
        "stops": 3,
        "prices":{
            "price_rub": 12450,
            "price_usd": 189.96,
            "price_eur": 167.31
        }
    }, {
        "id": 7,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "17:10",
        "arrival_date": "12.05.18",
        "arrival_time": "23:45",
        "carrier": "TK",
        "stops": 1,
        "prices": {
            "price_rub": 13600,
            "price_usd": 207.51,
            "price_eur": 182.76
        }
    }, {
        "id": 8,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "6:10",
        "arrival_date": "12.05.18",
        "arrival_time": "15:25",
        "carrier": "TK",
        "stops": 0,
        "prices": {
            "price_rub": 14250,
            "price_usd": 217.42,
            "price_eur": 191.49
        }
    }, {
        "id": 9,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "16:50",
        "arrival_date": "12.05.18",
        "arrival_time": "23:35",
        "carrier": "SU",
        "stops": 1,
        "prices": {
            "price_rub": 16700,
            "price_usd": 254.81,
            "price_eur": 224.42
        }
    }, {
        "id": 10,
        "origin": "VVO",
        "origin_name": "Владивосток",
        "destination": "TLV",
        "destination_name": "Тель-Авив",
        "departure_date": "12.05.18",
        "departure_time": "6:10",
        "arrival_date": "12.05.18",
        "arrival_time": "16:15",
        "carrier": "S7",
        "stops": 0,
        "prices": {
            "price_rub": 17400,
            "price_usd": 265.49,
            "price_eur": 233.83
        }
    }
]